name: Warhammer Daily
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "27 13 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install requests beautifulsoup4
      - run: python warhammer.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_AUTH_CODE: ${{ secrets.EMAIL_AUTH_CODE }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
